name: Recieve ping to update 'Website'
on:
  [repository_dispatch]
jobs:
  PONG:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
         curl \
         -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/Big-Install-Guide/Website/actions/workflows/generate-and-publish-website.yml
         -d '{"ref":"ref"}' 