name: Receive ping to update website
on:
  [repository_dispatch]
jobs:
  PONG:
    runs-on: ubuntu-latest
    steps:
      - name: '"Manually" update website'
        run: |
          curl \
          --request POST \
          --header "Accept: application/vnd.github.v3+json" \
          --user '${{ secrets.LIMITED_PAT }}' \
          --data '{"ref":"refs/heads/master"}' \
          --url "https://api.github.com/repos/Big-Install-Guide/Website/actions/workflows/generate-and-publish-website.yml/dispatches"