name: Recieve ping to update 'Website'
on:
  [repository_dispatch]
jobs:
  PONG:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}